---
- name: check /usr/local  is creat 
  shell: "ls /usr | grep local |wc -l"
  register: result
- name: create /usr/local dir
  file: path={{install_dir}} state=directory backup=yes
  when: result.stdout == '0'
- name: check redis-{{redis_verison}} is creat
  shell: "ls /usr/local | grep redis-{{redis_verison}} |wc -l"
  register: version
- name: copy redis package to  /usr/local/
  copy: src=redis-{{redis_verison}} dest={{install_dir}} backup=yes mode=755
  when: version.stdout == '0'

