---
- name: copy quickly dir to {{scripts_dir}}
  copy: src=quickly dest={{scripts_dir}} backup=yes mode=755
- name: copy scirpt to {{scripts_dir}} each dir
  template: src={{item.script}} dest="{{scripts_dir}}/quickly/{{item.dir}}/{{item.script}}" backup=yes mode=755
  with_items:
    - { script: 'check_update.sh', dir: 'autocheck'}
    - { script: 'close_alllogin.sh', dir: 'closelogin'}
    - { script: 'update_base.sh', dir: 'static_base'}
    - { script: 'open_alllogin.sh', dir: 'openlogin'}
