- hosts: login
  remote_user: root
  gather_facts: False
  roles:
    - login
- hosts: gate
  remote_user: root
  gather_facts: False
  roles:
    - gate
- hosts: logic
  remote_user: root
  gather_facts: False
  roles:
    - logic
- hosts: room
  remote_user: root
  gather_facts: False
  roles:
    - room
- hosts: fight
  remote_user: root
  gather_facts: False
  roles:
    - fight

