- name: create gate dir
  file: path={{huoping_dir}} state=directory backup=yes recurse=yes
- name: create scripts dir
  file: path={{scripts_dir}} state=directory backup=yes recurse=yes

- name: check gate daemon
  shell: "ps aux | grep '{{gate_server_dir}}'  |grep -v grep | wc -l"
  register: daemon
- name: copy gate data
  copy: src=gate_server dest={{huoping_dir}} backup=yes mode=755
  when: daemon.stdout == '0'
- name: copy gate config  and sh file
  template: src={{item}} dest={{gate_server_dir}} backup=yes mode=755
  with_items:
    - config.json
    - start.sh
    - stop.sh
  when: daemon.stdout == '0'
- name: copy start_gate_server.sh
  template: src=start_gate_server.sh  dest={{scripts_dir}}/start_gate_server{{gate_node_id}}.sh backup=yes mode=755
- name: copy stop_gate_server{{gate_node_id}}.sh
  template: src=stop_gate_server.sh  dest={{scripts_dir}}/stop_gate_server{{gate_node_id}}.sh backup=yes mode=755
- name: copy check_gate.sh
  template: src=check_gate.sh  dest={{scripts_dir}} backup=yes mode=755
#- name: start gate daemon
#  shell: "{{scripts_dir}}/start_gate_server{{gate_node_id}}.sh"
#  when: daemon.stdout == '0'
