- name: copy mysql source code to client
  copy: src={{ mysql_version }}.tar.gz dest=/root/{{ mysql_version }}.tar.gz owner=root group=root
- name: set mem variable
  shell: echo {{mem}}/4 | bc
  register: result
- name: set indb_size
  set_fact: indb_size="{{result.stdout}}"
- name: copy my.cnf to /etc
  template: src=my.cnf dest=/etc owner=root group=root
- name: copy mysql install script to client
  template: src=mysql_install.sh dest=/root/mysql_install.sh owner=root group=root mode=0755
- name: copy huopin sql data to /tmp
  template: src=db/{{item}}.sql dest=/tmp owner=root group=root mode=0755
  with_items:
    - contra_auth
    - contra_base
    - contra_stats
    - contra_admin
    - contra_battlelog
    - insert_auth_game_server
