- name: create logic dir
  file: path={{huoping_dir}} state=directory backup=yes recurse=yes
- name: create logic dir
  file: path={{scripts_dir}} state=directory backup=yes recurse=yes

- name: check logic daemon
  shell: "ps aux | grep '{{logic_server_dir}}'  |grep -v grep | wc -l"
  register: daemon
- name: copy logic data
  copy: src=logical_server dest={{huoping_dir}} backup=yes mode=755
  when: daemon.stdout == '0'
- name: copy logic config  and sh file
  template: src={{item}} dest={{logic_server_dir}} backup=yes mode=755
  with_items:
    - config.json
    - start.sh
    - stop.sh
  when: daemon.stdout == '0'
- name: copy start_logic_server.sh
  template: src=start_logical_server.sh  dest={{scripts_dir}}/start_logical_server{{logic_node_id}}.sh backup=yes mode=755
- name: copy stop_logic_server{{logic_node_id}}.sh
  template: src=stop_logical_server.sh  dest={{scripts_dir}}/stop_logical_server{{logic_node_id}}.sh backup=yes mode=755
- name: copy check_logic.sh
  template: src=check_logic.sh  dest={{scripts_dir}} backup=yes mode=755
#- name: start logic daemon
#  shell: "{{scripts_dir}}/start_logical_server{{logic_node_id}}.sh"
#  when: daemon.stdout == '0'
